version: '3'

services:

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minioaccess
      - MINIO_SECRET_KEY=miniosecret
    volumes:
      - "minio:/data"
    command: server /data

  airflow-meta:
    image: postgres
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_PASSWORD=pgsecret
    volumes:
      - "airflow-meta:/var/lib/postgresql/data"

  airflow-migrations:
    build:
      context: .
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://postgres:pgsecret@airflow-meta/postgres
    depends_on:
      - airflow-meta
    restart: on-failure
    command: upgradedb

  airflow-webserver:
    build:
      context: .
    volumes:
      - "./dags/:/usr/local/airflow/dags"
      - "./plugins/:/usr/local/airflow/plugins"
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://postgres:pgsecret@airflow-meta/postgres
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__REMOTE_LOGGING=True
      - AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER=s3://airflow/logs
      - AIRFLOW__CORE__REMOTE_LOG_CONN_ID=minio
      - AIRFLOW__CORE__ENCRYPT_S3_LOGS=False
    depends_on:
      - airflow-meta
      - airflow-migrations
    ports:
      - "8080:8080"
    restart: always
    command: webserver

  airflow-scheduler:
    build:
      context: .
    volumes:
      - "./dags/:/usr/local/airflow/dags"
      - "./plugins/:/usr/local/airflow/plugins"
    environment:
      - AIRFLOW_CONN_MINIO=s3://minioaccess:miniosecret@airflow?host=http%3A//minio%3A9000
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://postgres:pgsecret@airflow-meta/postgres
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__REMOTE_LOGGING=True
      - AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER=s3://airflow/logs
      - AIRFLOW__CORE__REMOTE_LOG_CONN_ID=minio
      - AIRFLOW__CORE__ENCRYPT_S3_LOGS=False
    depends_on:
      - airflow-meta
      - airflow-migrations
    restart: always
    command: scheduler

volumes:
  airflow-meta:
  minio:
